apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: cloudvoyage
type: Opaque
data:
  # user: admin | password: password123
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQxMjM=