apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudvoyage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # Docker Hub image
          image: harjotsingh2k19/cloudvoyage-frontend:v1
          ports:
            - containerPort: 80